// Generated by CoffeeScript 1.3.3
(function() {
  var {%= js_safe_name %};

  if (typeof {%= js_safe_name %} === "undefined" || {%= js_safe_name %} === null) {
    {%= js_safe_name %} = this.{%= js_safe_name %} = {};
  }

  {%= js_safe_name %}.config = {
    version: "0.0.1",
    env: "dev"
  };

}).call(this);
