// Generated by CoffeeScript 1.3.3
(function() {

  {%= js_safe_name %}.initRouter = function() {
    var handlers, options;
    return handlers = options = this.router = new $.mobile.Router({}, handlers, options);
  };

}).call(this);
